keywords:
  high_priority:
    - gravitational
    - black hole
    - neutron star
  medium_priority:
    - cosmology
    - relativity
    - dark matter
  low_priority: []

arxiv_categories:
  - gr-qc
  - astro-ph.CO

max_articles: 10
min_relevance: 0  # 0 = accept all, 1-5 to filter
