keywords:
  high_priority:
    - "gravitational wave"
    - "black hole"
    - "LIGO"
    - "neutron star"
    - "gravitational lensing"
    - "merger"
  
  medium_priority:
    - "cosmology"
    - "dark matter"
    - "dark energy"
    - "relativity"
    - "spacetime"
    - "gravity"
    - "Einstein"
    - "metric"
    - "curvature"
    - "singularity"
    - "horizon"
    - "wormhole"
  
  low_priority:
    - "numerical"
    - "quantum"
    - "field theory"
    - "GR"
    - "cosmological"

arxiv_categories:
  - gr-qc
  - astro-ph.CO
  - astro-ph.HE

max_articles: 20
min_relevance: 1  # Accept everything with at least 1 keyword match
